language: java
deploy:
  provider: heroku
  api_key:
    secure: ZCFWNTHrhZ9jRBBHn9ZOeIxYoYbJIGkYFC9IGmagbqOdKnIRb64eNsTj5yw+v/mvtqxK0yhonGK2e+oixOPt1/31AQQmnu6kmDOpYozc+VLePk5PMgIJ/eo68IXH2dkz18QXr3mW+1vriQWLUPK40aHlcLKBaQeymecaZOjf05Fze2euGLL+eh4vRzClTrel+mVDP76KD1ksTh6Hl8hmQ3LqTnY774BKHWRuNf4vq63xAXfejwGNsna57bNFFEMzOa3eV0NSDzzWCq5dGNMzT5prYdJjkYN8kGDBuxRP9cFkbFWD4ihxapdN1Tg3pYrGiKglmF1OjE06g9Nqh6i9V0ci1G/VVDXfYESPogcY3uGqYwj2Lm9SdjoLlZG5pwtcL7BLdjYahHKEAa0vEM+20lZNw8C0RBm+KgUC8ezeSW1BlVqb2x5VVA8Ru4QNOcNhm1del2X7do6flHt14bT236dl4orGRk63PiIE9HPUnlUKmv2kliGXBx6cjKfCMxdM3OLSWGVk+i+k9URzw+sh75vIucuE6VajmOkZ+doxgncdlor0TgTxKWwX6xteimq2wLxe5qLR6xj074NpyOmyFMQ2MbMy7ZnxzGJthYjVm1zo5D+N79udMuagJF8wlgVNRpTjrxoWVi9G5zSel8Fq3CjYjb7QTBSrjYY5Tx9FcXE=
  app: secure-anchorage-69402
  on:
    repo: justasmalinauskas/PlanuotojasPro
